### ISSUE TITLE
[FEAT] Stackoverflow Integration

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#10]
I would like to integrate StackOverflow at some point.

We could have commands like

`$soSearch xyz` - retrieves top 5 results for searched question
`$soJobs xyz` - retrieves top 5 job results for searched job

maybe even more?

**Comment by cannap** [comment]
Hi, i know this package https://github.com/santinic/how2 maybe this one will help to implement this

**Comment by jamen** [comment]
Nice find @cannap.  However, after taking a look, it doesn't seem like it is designed as a more generic library.  All their code uses `console.log` internally, has `"preferGlobal"`, and the `"main"` entry is also broken.

Perhaps we could do some PRs and collaborate with them? otherwise, maybe start a different package. (willing to collab with someone on that)

**Comment by goonit** [comment]
If SO doesn't have a specific API or module, why don't we just go one level higher and integrate a Google search.

**Comment by cannap** [comment]
@goonit  this is how2 works and yea i know the package is not made to reuse :/ but i just posted this for the idea
