### ISSUE TITLE
Implement Bot Controller core plugin

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#139]
### Todo

* [x] Prune Plugin
  * [x] Pruning x messages
  * [x] Pruning x messages of user y

**Comment by bdbch** [comment]
I thought about it - controlling the avatar and the game should be enough (since the bots name it self is the username and should be set on the API itself. Nicknames should be set by the server owners themself)

**Comment by bdbch** [comment]
@AlphaStyle you could think of another feature which could be set by the bot controller coreplugin? I'm currently working on it on a seperate branch and just implemented an option to change the bots game on startup.

Username, Nickname and Avatar doesn't really make sense.

**Comment by AlphaStyle** [comment]
I agree on the Username, Nickname and Avatar, because that is something you do when you get the token from discord. (but than again, it is nice to have the option ;) )

This is the most basic I can find in the Discord.js API - [PresenceData](https://discord.js.org/#/docs/main/stable/typedef/PresenceData)
Maybe make it possible to create an Invite link?

Is creating / deleting roles and channels and kicking and banning maybe a little too much?

**Comment by bdbch** [comment]
I think creating an invite link isn't really a usecase, but I could think of pruning messages or something like this.

So
- Pruning Messages
- Sending out Announcements (maybe?)

banning and kicking are implemented + reasons in the audit log now so no need for that.

**Comment by AlphaStyle** [comment]
Pruning Messages could be a cool feature!

If your bot is on multiple servers and you would like to make an announcement on all of them, then yes, that would be a good feature. But it has to be a user friendly feature :smile: Cause the announcement should be in a specific channel, right? Not just spam a random channel.
