### ISSUE TITLE
[BUG] cordlr file

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#15]
Shouldn't the /bin/cordlr file be called "cordlr.js"?

**Comment by jamen** [comment]
Not in particular.  It's uncommon for linked `bin` files to have an extension, and the other files are mainly just helpers to keep that file more clean.

There is also a shebang inside the file (`#/usr/bin/env node`), which would execute it as JS and also syntax highlight, or do anything to let your OS identify it as JavaScript.  That is how it works on Linux for me, and I believe Windows as well.

At the end of the day, it doesn't really matter, because the symbolic link that npm creates from the package.json `"bin"` property has no extension, so it would all function the same no matter what you named it.

**Comment by bdbch** [comment]
Ah I see, nvm this is closed!
