### ISSUE TITLE
[DISS] Callbacks vs promises

### ISSUE THREAD

**Issue by mees-** [Devcord/cordlr-cli#74]
I think we need to decide whether we will be using promises or callbacks for async control.

**Comment by mees-** [comment]
I am in favor of promises because they are future proof, look nicer (in my opinion) and discord.js uses them as well so if we use them plugin creators won't be forced to mix them in the same context

**Comment by turbits** [comment]
I think promises are the way to go too, for above reasons. also dem `a e s t h e t i c s`

**Comment by jamen** [comment]
I don't like maintaining promises inside of code, after having done many collaborative and solo projects with them.  I prefer a callback + factory system, it actually turns out very clean (more than promises in my opinion).

However, given that discord.js is based mostly on top of promises, we may as well use them for consistency between everything, since we have no control over that.

I mean, I guess we do...  But I don't feel like writing any sort of wrappers around discord.js.  Avoids us having to write complex documentation and we can cite discord.js easily.
