### ISSUE TITLE
Improve installation workflow and use own configuration file for cordlr

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#95]
My feedback to the latest changes on the bot:
- if no token is in the config, there should be an error message
- the configuration for the bot should not live in the package.json, I don't like mixing things up. The package json should only be used for npm or package informations like the version and package name
- the configuration shouldn't be done manually. Adding cordlr plugins should still run through a proxy command which automatically adds the installed plugin as an index into the config

right now the installation os to complicated since we could automate it

**Comment by mees-** [comment]
As a response to your last point: maybe we should have the loader scan the `node_modules` folder for plugins automatically, so we don't even need to specify them in a config

**Comment by jamen** [comment]
Agreed on the first point.  The other points are trivial in my opinion, so I'll leave that up to other people to implement.  However, speaking for myself:
1. I find it more clean when all the information is packaged into one place.  Especially with how our system is reliant on npm now.  You will inevitably end up with a `package.json` if you want to save any 3rd party plugins, and literally nothing else would be in it (since it is nothing you are publishing), so we might as well use it and stay organized in the process (because it eliminates the need for a second file).
2. I don't really see a problem with loading plugins manually.  I view it almost as an authorization/confirmation step as the user.  Sure, you could do `cordlr load` or something, but it is literally one line in the config...  You probably already have the config open anyways to edit plugin settings and whatnot.

**Comment by bdbch** [comment]
I understand that but still the package.json is a special file created and used by npm. We're using it a strange way and i don't really like it. The bot should have his own configuration for bot configuration and plugin configuration.

this also helps with visibility later when more plugins are installed and more configuration is added. No npm-keys in the configs etc.

Also having "everything" in one place can also be bad, especially with a plugin concept. plugins should actually have their own configuration which could also be automatically generated on runtime. This way, you can remove or add configurations automatically from the CLI. right now It's kind of annoying that there is so much custom stuff to do.

Why should a user open the package.json and put the plugin-configuration there manually if the bot developer could just add a sample-configuration which is going to be copied to the CWD and used for the bot configuration.

**Comment by mees-** [comment]
I sort of agree with separating the config from the package.json I think we should encourage plugins to put their config inside the cordlr config like this:

``` js
{
  // cordlr config
  "token": "abc",
  "plugins": ["a","b","c"],
  "a": { //  config for plugin a
    "adminRole": "123456789"
  }
}
```

**Comment by mees-** [comment]
Maybe not exactly like that, maybe let plugins create their own confg in a special key in the cordlr config like `config.pluginConfig.a.adminRole = '123456789'`

**Comment by jamen** [comment]
I get why and how the config wants to be split up, and I'm saying I disagree with it.  Which is why cordlr took this path to begin with and eliminated the need for multiple files.  (I think you're taking the convenience for granted here!)

Nothing explicit says we can't use the `package.json`, either.  I've seen other node-based software do similar things using this file, which is partly why I made the transition as well.

I'm for _usability_ over _practice_ on this one.  Splitting the configuration into many files will make the bot harder to reason about, complicated to continue developing, and unable to share information between them easily.

There is certain things I think plugins should be agnostic of  so they are easier to look at and understand, use independently, and remove a lot of bloat in the process.  Reading a single config and sharing it around is one of these things.

I could continue to rant more reasons, but I'll summarize it into something simple:  I can foresee lots of problems in future development with such a fragmented configuration system, as well as many lost benefits to the current system.

I did put thought into that method, the current method, and other methods before going down this route.

**Comment by jamen** [comment]
It's not my sole decision whether stuff like that is implemented, so I'll leave it up to other people to do...  I'll give my reasoning why we shouldn't, though.

**Comment by jamen** [comment]
Perhaps we could go on an idea that I believe @mees- mentioned briefly to me in chat...  

Have configs be read by loaders so we can do opinionated methods, and avoid this whole problem...  I still think this should be the default method though.  It's simple and nice.

EDIT: Although, then we have to figure out how to determine the loader...  Since that depends on a config.

**Comment by bdbch** [comment]
I like the idea of @mees- 

```
{
  // cordlr config
  "token": "abc",
  "plugins": ["a","b","c"],
  "a": { //  config for plugin a
    "adminRole": "123456789"
  }
}
```

could be one cordlr.json which is used for all cordlr-specific options while the package.json is only used by npm only.

That way we can also make configuration from the cordlr-cli way easier.

**Comment by mees-** [comment]
@jamen the idea i mentioned in chat was about having a separate module determine the config, an `initiator`

@db2k That idea can be implemented in a package.json context aswell though

but to come back to the main discussion, im not entirely sure which i prefer, i'll leave that up to you

**Comment by bdbch** [comment]
To come back to this issue, I still think the **package.json** should be seperated from the cordlr configuration.

* `package.json` is usually only used by nodejs or yarn
* `.cordlr.json` would explain what the file is and is used like this for other tools too (See vscode and their `.vscode` folder for configurations)
